const songDisplay = document.getElementById('song');
const changeBtn = document.getElementById('changeSong');
const albumDisplay = document.getElementById('album');
let songs = [
  ['椎名林檎', [
    'skf 幸福論',
    'skf すべりだい',
    'skb 歌舞伎町の女王',
    'skb アンコンディショナル・ラブ',
    'skf 時が暴走する',
    'skb 実録-新宿にて- 丸の内サディスティック~歌舞伎町の女王',
    'skk ここでキスして。',
    'skk 眩暈',
    'skk リモートコントローラー',
    'shn 本能',
    'shn あおぞら',
    'shn 輪廻ハイライト',
    'sgb ギブス',
    'sgb 東京の女',
    'sgb Σ',
    'stt 罪と罰',
    'stt 君ノ瞳ニ恋シテル',
    'stt 17',
    'smy 真夜中は純潔',
    'smy シドと白昼夢',
    'smy 愛妻家の朝食',
    'sst 迷彩 ~戦後最大級ノ暴風雨圏内歌唱~',
    'sst 茎(STEM) ~大名遊ビ編~',
    'sst 意識 ~戦後最大級ノ暴風雨圏内歌唱~',
    'srn りんごのうた',
    'srn la salle de bain',
    'srn リンゴカタログ ~黒子時代再編纂~',
    'skn この世の限り',
    'skn 錯乱 ONKIO ver.',
    'skn カリソメ乙女 HITOKUCHIZAKA ver.',
    'sar ありあまる富',
    'sar SG ~Superficial Gossip~',
    'ska カーネーション',
    'ska 私の愛するひと',
    'ska 人生は思い通り',
    'sir いろはにほへと',
    'sir 孤独のあかつき',
    'sni NIPPON',
    'sni 逆さに数えて',
    'ssj 至上の人生',
    'ssj どん底まで',
    'snk 長く短い祭',
    'snk 神様、仏様',
    'swh 私は猫の目',
    'swh さらば純情',
    'sng 人間として',
    'sng 紅海月の夜',
    'ssn 芒に月',
    'ssn 松に鶴',
    'sjk 実験中',
    'sjk 白日のもと',
    'szc やっつけ仕事',
    'szc ギャンブル',
    'szc Jｪﾁ~ｯじoTMｳ',
    'szc メロウ',
    'szc 不幸自慢',
    'szc 喪@ CｪNｺ瑠ｦｭWｧ',
    'szc 膨らんできちゃった',
    'szc はいはい',
    'szc 光合成',
    'ahi 自由へ道連れ',
    'ahi ありきたりな女',
    'asd ジユーダム',
    'asd 目抜き通り',
    'agm おいしい季節',
    'agk おとなの掟',
    'asd 獣ゆく細道',
    'srm 浪漫と算盤 TYO ver.',
    'ahj いとをかし',
    'amz 正しい街',
    'amz 丸の内サディスティック',
    'amz 幸福論(悦楽編)',
    'amz 茜さす 帰路照らされど...',
    'amz 積木遊び',
    'amz 同じ夜',
    'amz 警告',
    'amz モルヒネ',
    'ass 虚言症',
    'ass 浴室',
    'ass 弁解ドビュッシー',
    'ass 闇に降る雨',
    'ass アイデンティティ',
    'ass 罪と罰',
    'ass ストイシズム',
    'ass 月に負け犬',
    'ass サカナ',
    'ass 病床パブリック',
    'ass 依存症',
    'akr 宗教',
    'akr ドツペルゲンガー',
    'akr 迷彩',
    'akr おだいじに',
    'akr やっつけ仕事',
    'akr 茎',
    'akr とりこし苦労',
    'akr おこのみで',
    'akr 意識',
    'akr ポルターガイスト',
    'akr 葬列',
    'ahs 錯乱 TERRA ver.',
    'ahs ハツコイ娼女',
    'ahs パパイヤマンゴー',
    'ahs カリソメ乙女 TAMEIKESANNOH ver.',
    'ahs 花魁',
    'asm 流行',
    'asm 労働者',
    'asm 密偵物語',
    'asm 〇地点から',
    'asm カリソメ乙女(DEATH JAZZ ver.)',
    'asm 都合のいい体',
    'asm 旬',
    'asm 二人ぼっち時間',
    'asm マヤカシ優男',
    'asm 尖った手口',
    'asm 色恋沙汰',
    'asm 凡才肌',
    'asm 余興',
    'asm 丸の内サディスティック EXPO ver.',
    'agm 主演の女',
    'agm 渦中の男',
    'agm プライベイト',
    'agm 青春の瞬き',
    'agm 真夏の脱獄者',
    'agm 望遠鏡の外の景色',
    'agm 決定的三分間',
    'agm カプチーノ',
    'agm 雨傘',
    'agm 日和姫',
    'agm 幸先坂',
    'ahi 静かなる逆襲',
    'ahi 走れゎナンバー',
    'ahi 赤道を越えたら',
    'ahi JL005便で',
    'ahi ちちんぷいぷい',
    'ahi 今',
    'agk 人生は夢だらけ',
    'agk おいしい季節',
    'agk 少女ロボット',
    'agk 暗夜の心中立て',
    'agk 薄ら氷心中',
    'agk 華麗なる逆襲',
    'agk 野生の同盟',
    'asd 鶏と蛇と豚',
    'asd マ・シェリ',
    'asd 駆け落ち者',
    'asd TOKYO',
    'asd 急がば回れ',
    'asd あの世の門',
    'any 公然の秘密',
    'ahj ちりぬるを',
    'ahj 私は猫の目 album ver.',
    'ahj 生者の行進',
    'ahj 人間として',
    'ahj 初KO勝ち',
    'ahj 公然の秘密 album ver.',
    'ahj 浪漫と算盤 TYO album ver.',
    'ahj 茫然も自失',
    'ahj ドラ1独走',
    'ahj さらば純情 album ver.',
    'ahj 余裕の凱旋',
    'ahj いとをかし album ver.',
    'ahj ほぼ水の泡'
  ]],
  ['東京事変', [
    'sgb 群青日和',
    'sgb その淑女ふしだらにつき',
    'sgb 顔',
    'ssn 遭難',
    'ssn ダイナマイト',
    'ssn 心',
    'ssr 修羅場',
    'ssr 恋は幻',
    'ssr 落日',
    'sos OSCA',
    'sos ピノキオ',
    'sos 鞄の中身',
    'skr キラーチューン',
    'skr BB.Queen',
    'skr 体',
    'snd 能動的三分間',
    'snd 我慢',
    'sso 空が鳴っている',
    'sso 女の子は誰でも',
    'aki 林檎の唄',
    'aki 群青日和',
    'aki 入水願い',
    'aki 遭難',
    'aki クロール',
    'aki 現実に於て',
    'aki 現実を嗤う',
    'aki サービス',
    'aki 駅前',
    'aki 御祭騒ぎ',
    'aki 母国情緒',
    'aki 夢のあと',
    'aad 秘密',
    'aad 喧嘩上等',
    'aad 化粧直し',
    'aad スーパースター',
    'aad 修羅場 adult ver.',
    'aad 雪国',
    'aad 歌舞伎',
    'aad ブラックアウト',
    'aad 黄昏泣き',
    'aad 透明人間',
    'aad 手紙',
    'abr ランプ',
    'abr ミラーボール',
    'abr 金魚の箱',
    'abr 私生活',
    'abr OSCA',
    'abr 黒猫道',
    'abr 復讐',
    'abr 某都民',
    'abr SSAW',
    'abr 月極姫',
    'abr 酒と下戸',
    'abr キラーチューン',
    'abr メトロ',
    'asp 生きる',
    'asp 電波通信',
    'asp シーズンサヨナラ',
    'asp 勝ち戦',
    'asp FOUL',
    'asp 雨天決行',
    'asp 能動的三分間',
    'asp 絶体絶命',
    'asp FAIR',
    'asp 乗り気',
    'asp スイートスポット',
    'asp 閃光少女',
    'asp 極まる',
    'adh 天国へようこそ',
    'adh 絶対値対相対値',
    'adh 新しい文明開化',
    'adh 電気のない都市',
    'adh 海底に巣くう男',
    'adh 禁じられた遊び',
    'adh ドーパミント！',
    'adh 恐るべき大人達',
    'adh 21世紀宇宙の子',
    'adh かつては男と女',
    'adh 空が鳴っている',
    'adh 風に肖って行け',
    'adh 女の子は誰でも',
    'aco 今夜はから騒ぎ',
    'aco 怪ホラーダスト',
    'aco タイムカプセル',
    'aco sa＿i＿ta',
    'aco ほんとのところ',
    'atk 三十二歳の別れ',
    'atk 禁じられた遊び',
    'atk かつては男と女',
    'atk キラーチューン',
    'atk OSCA',
    'atk ミラーボール',
    'atk 復讐',
    'atk ピノキオ',
    'atk 閃光少女',
    'atk 透明人間',
    'atk 丸の内サディスティック',
    'atk スーパースター',
    'atk 群青日和',
    'atk 夢のあと',
    'asy ハンサムすぎて',
    'asy ただならぬ関係',
    'any 選ばれざる国民',
    'any うるうるうるう',
    'any 現役プレーヤー',
    'any 猫の手は借りて',
    'any 永遠の不在証明',
    'amy 孔雀',
    'amy 毒味',
    'amy 紫電',
    'amy 命の帳',
    'amy 黄金比',
    'amy 青のID',
    'amy 闇なる白',
    'amy 赤の同盟',
    'amy 銀河民',
    'amy 獣の理',
    'amy 緑酒',
    'amy 薬漬',
    'amy 一服',
    'asg 原罪と福音',
    'asg 仏だけ徒歩'
  ]]
];
const albumTable = {
  '椎名林檎': {
    skf: '幸福論 (1998)',
    skb: '歌舞伎町の女王 (1998)',
    skk: 'ここでキスして。 (1999)',
    shn: '本能 (1999)',
    sgb: 'ギブス (2000)',
    stt: '罪と罰 (2000)',
    smy: '真夜中は純潔 (2001)',
    sst: '茎(STEM) ~大名遊ビ編~ (2003)',
    srn: 'りんごのうた (2003)',
    skn: 'この世の限り (2007)',
    sar: 'ありあまる富 (2009)',
    ska: 'カーネーション (2011)',
    sir: 'いろはにほへと／孤独のあかつき (2013)',
    sni: 'NIPPON (2014)',
    ssj: '至上の人生 (2015)',
    srm: '浪漫と算盤 TYO ver. (2019)',
    snk: '長く短い祭／神様、仏様 (2015)',
    swh: '私は猫の目 (2023)',
    sng: '人間として (2024)',
    ssn: '芒に月 (2025)',
    sjk: '実験中 (2025)',
    szc: '絶頂集 (2000)',
    amz: '無罪モラトリアム (1999)',
    ass: '勝訴ストリップ (2000)',
    akr: '加爾基 精液 栗ノ花 (2003)',
    ahs: '平成風俗 (2007)',
    asm: '三文ゴシップ (2009)',
    agm: '逆輸入 ~港湾局~ (2014)',
    ahi: '日出処 (2014)',
    agk: '逆輸入 ~航空局~ (2017)',
    asd: '三毒史 (2019)',
    ahj: '放生会 (2024)',
    akj: '禁じ手 (2026)',
    any: 'ニュートンの林檎 ~初めてのベスト盤~ (2019)'
  },
  '東京事変': {
    sgb: '群青日和 (2004)',
    ssn: '遭難 (2004)',
    ssr: '修羅場 (2005)',
    sos: 'OSCA (2007)',
    skr: 'キラーチューン (2007)',
    snd: '能動的三分間 (2009)',
    sso: '空が鳴っている／女の子は誰でも (2011)',
    aki: '教育 (2004)',
    aad: '大人 (2006)',
    abr: '娯楽 (2007)',
    asp: 'スポーツ (2010)',
    adh: '大発見 (2011)',
    aco: 'color bars (2012)',
    atk: '東京コレクション (2012)',
    asy: '深夜枠 (2012)',
    any: 'ニュース (2020)',
    amy: '音楽 (2021)',
    asg: '総合 (2021)'
  }
};
let flatMap = [];
let flatMapAlbum = [];
let albumName = '';
songs.forEach(artist => {
  const artistName = artist[0];
  artist[1].forEach(song => {
    flatMap.push(`${artistName} - ${song.slice(4, song.length)}`);
    flatMapAlbum.push(['SINGLE  ', 'ALBUM  '][Number(song[0]==='a')] + albumTable[artistName][song.slice(0, 3)]);
  });
});
songs = null;

function randomSong() {
  const t = Math.floor(Math.random() * flatMap.length);
  songDisplay.innerText = flatMap[t];
  albumDisplay.innerText = flatMapAlbum[t];
}

changeBtn.onclick = randomSong;
randomSong();